import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import QueryProiver from './providers/react-query';
import { Toaster } from '@/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // console.log(children);
  return (
    <html lang='en'>
      <QueryProiver>
        <body className={' bg-zinc-900'}>
          <main>{children}</main>
          <Toaster />
        </body>
      </QueryProiver>
    </html>
  );
}
