import { Toaster } from '@/components/ui/toaster';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import QueryProiver from './providers/react-query';
import AxiosInterceptor from './providers/AxiosInterceptor';
import { UserProvider } from './providers/UserContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <UserProvider>
        <QueryProiver>
          <AxiosInterceptor />
          <body className={' bg-zinc-900'}>
            <main>{children}</main>
            <Toaster />
          </body>
        </QueryProiver>
      </UserProvider>
    </html>
  );
}
